### ISSUE TITLE
single-export modules breaking it

### ISSUE THREAD

**Issue by mattdesl** [browserify/static-module#3]
I have code like this:

``` js
var foo = require('foo')

console.log(foo(__dirname+'/blah.png'))
console.log(foo(__dirname+'/blah2.png'))
console.log(foo(__dirname+'/blah3.png'))
```

``` js
//static setup
var sm = staticModule(
        { 'foo': test },
        { vars: vars }
)
```

And using a brfs-like inlining transform, it spits the inlined content to after the 2nd and 3rd console log expressions. However, only by changing my static module to use a function, like `foo.bar()`, and changing my static module setup, it all works perfectly. 

``` js
//static setup
var sm = staticModule(
        { 'foo': { bar: test } },
        { vars: vars }
)
```

Any ideas?

**Comment by RangerMauve** [comment]
Wait, doe single export modules work, then?
