### ISSUE TITLE
Update vulnerable dependency (static-eval)

### ISSUE THREAD

**Issue by cp4r3z** [browserify/static-module#34]
https://nodesecurity.io/advisories/548

Remediation: Upgrade to static-eval 2.0

**Comment by pirosikick** [comment]
👍

**Comment by yoshuawuyts** [comment]
PR welcome!

**Comment by danez** [comment]
Without a changelog of static-eval@2 it is rather hard to figure out what the breaking change is and how it affects this module.

**Comment by yoshuawuyts** [comment]
@danez I think if the tests pass we should merge it — it's trading off a known bug against a hypothetical bug; this is a fix. 

Agree it'd be nice if we could test this ahead of time on dependents, but we don't have the infra setup for that now, and don't think we should hold off merging this patch until then. Hope this makes sense!

**Comment by dyaa** [comment]
Any updates !

**Comment by cp4r3z** [comment]
Looks like PR https://github.com/substack/static-module/pull/36 might also address the problem, but is more involved. Sounds like @lguzzon has the tests succeeding as well.
