### ISSUE TITLE
Acorn 5.5.1 dependant package vulerability issue in static-module 

### ISSUE THREAD

**Issue by jerin** [browserify/static-module#62]
We have a Xray scanner to identify package/inner package vulnerabilities. While scanning static-module , the scanner reporting an acorn@5.5.1 package vulnerability from a file which is currently being used by static module.

Path is package/bench/input.js 
Line number 5269

Acorn 5.5.1 Vunerability description: acorn contain an infinite loop condition in regexp.js that is triggered when handling UTF_16 surrogates while validating reqular expressions.

Please check this issue.

Thanks
Jerin john

**Comment by goto-bus-stop** [comment]
that file is input for a benchmark, it is never executed under any circumstance, so this is a false positive.

**Comment by jerin** [comment]
Thank you
