### ISSUE TITLE
Security vulnerability noticed in word-wrap 1.2.3 

### ISSUE THREAD

**Issue by TanushreeB2611** [browserify/static-module#66]
Hi Team,
I am blocked due to word-wrap 1.2.3, which is an indirect dependency in our app. 
Path: static-module/3.0.4 >> escodegen/1.14.3 >> optionator/0.8.3 >> word-wrap/1.2.3.
In npm, I can see latest escodegen version available is 2.1.0 whereas static-module is using 1.11.1. Request you to upgrade the version for this package.

**Comment by TanushreeB2611** [comment]
Team, any update on the issue ?

**Comment by goto-bus-stop** [comment]
static-module users were never affected by this vulnerability (that code is unused), but static-eval now uses escodegen 2.x so it should no longer appear.
